spring:
  application:
    name: eureka-service
server:
  port: 8085
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8085/eureka
    server:
      waitTimeInMsWhenSyncEmpty: 0